config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get "/users",to: redirect('users/sign_up')
  resources :stories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
   def index
   end
   def users
   end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_story, only: [:edit,:update,:destory]
    def index
     @stories = current_user.stories.order(created_at:"desc")
    end

    def new
     @story = current_user.stories.new
    end

    def create
     @story = current_user.stories.new(story_params)
        if @story.save
            redirect_to stories_path,notice:'投稿しました'
        else
        　　render :new
        end
    end

    def edit
    end
    
    def update
     if @story.update(story_params)
        redirect_to stories_path, notice: '文章更新成功'
     else
        render :edit
     end
    end

    private
    def find_story
      @story = current_user.stories.find(params[:id])
    end    

    def story_params
      params.require(:story).permit(:title,:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMedium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/frontend/navbar" %>
    <div class="container">
     <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>hi</h1>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path,class:'navbar-item' do %>
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>
    <% end %>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
  
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                  <%= current_user.email %> 
                </a>
            <div class="navbar-dropdown">
              <%= link_to "個人資料",edit_user_registration_path	,class:"navbar-item"%>
              <%= link_to "新しい記事",new_story_path		,class:"navbar-item"%>
              <%= link_to "記事リスト",stories_path		,class:"navbar-item"%>
              <hr class="navbar-divider">
              <%= link_to  "ログアウト", destroy_user_session_path, class: 'navbar-item',method:'delete', data:{confirm:'ログアウトしましょうか？'} %>              
            </div>
          </div>          
           
           
          <% else %>
              <%= link_to "登録", new_user_registration_path,class:"button is-primary"%>
              <%= link_to "ログイン",user_session_path, class:"button is-light",method:'post'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/stories/_form.html.erb
<%= form_for(story) do |form| %>
 <div class="field">
  <%= form.label :title, "テーマ" %>
  <%= form.text_field :title, class:"input is-primary is-medium" %>
 </div>
 <div class="field">
  <%= form.label :title, "内容" %>
  <%= form.text_area :content,rows:10, class:"textarea is-primary is-medium" %>
 </div>
 <div class="field">
  <%= form.submit '未完成保存', class:'button is-dark' %>
  <%= form.submit '投稿', class:'button is-primary' %>
 </div>

<% end %>

app/views/stories/edit.html.erb
<h1 class="title">Edit Story</h1>

<%= render 'form',story: @story %>

app/views/stories/index.html.erb
<h1 class="title">記事リスト</h1>

<% @stories.each do |story| %>
 <h2 class="title"><%= story.title %></h2>
 <p><%= story.content %></p>
 <p>last edit time <%= time_ago_in_words(story.updated_at) %></p>
 <%= link_to "edit",edit_story_path(story),class: 'button is-text is-small' %>
 <%= link_to "delete",story,method:"delete",data:{ confirm:'確認刪除'} ,class: 'button is-danger is-small'%>
 <hr>
<% end %>

app/views/stories/new.html.erb
<h1 class="title">新增故事</h1>

<%= render 'form' , story: @story%>